name: CI

on:
  push:
    branches:
      - '4.x'
      - '4.next'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

env:
  LANG: en_US.UTF-8

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        doc-type: ['HTML', 'EPUB', 'PDF']

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install packages
      run: |
        sudo apt update
        sudo apt install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-lang-all

    - name: Build Docs
      run: |
        if [[ ${{ matrix.doc-type }} == 'HTML' ]]; then make html SPHINXOPTS='-W --keep-going'; fi
        if [[ ${{ matrix.doc-type }} == 'EPUB' ]]; then make epub; fi
        if [[ ${{ matrix.doc-type }} == 'PDF' ]]; then make latex; fi
